import React ,{useState,useEffect,Component}from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header/header'
import Footer from '../../components/footer/footer'
import Image from 'next/image'
import {getProfilesName,getCompanyData} from '../../lib/partenaire'
import { Map, GoogleApiWrapper, InfoWindow, Marker } from 'google-maps-react';

const key = "AIzaSyBeM-wkqt3uIlMXGxnCHAvlsI8EBqXLOQI"



class index extends Component {

    state={

        mapStyles : {
            width: '100%',
            height: '100%',
            overflow: 'hidden',
            position:'relative'
        },
        location : JSON.parse(`${this.props.data.profile.company_location}`),
        showingInfoWindow: false,  // Hides or shows the InfoWindow
        activeMarker: {},          // Shows the active marker upon click
        selectedPlace: {}
    }

    onMarkerClick = (props, marker, e) =>
        this.setState({
            selectedPlace: props,
            activeMarker: marker,
            showingInfoWindow: true
     });

    onClose = props => {
        if (this.state.showingInfoWindow) {
            this.setState({
                showingInfoWindow: false,
                activeMarker: null
            });
        }
    };

    customImgLoader = ({ src }) => {
        return `${src}`
    }


    render() {

        return (
            <div className="recruteur">

                <div className="interface-layout">
                    <Head>
                        <title>A recruit | {this.props.data.profile.company_name}</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    {/*---------------*/}
                    <Header
                    />
                    {/*---------------*/}
                    
                    <main className="body">

                        <div className="top">
                            <div className="title white">
                                <div>
                                    <span>{this.props.data.profile.company_activity}</span>
                                </div>
                                <div>
                                    <br></br>
                                    {this.props.data.profile.company_name}
                                </div>
                            </div>

                            <div className="preview">
                                <div><span>{this.props.data.profile.company_name}</span></div>
                                <br></br>
                                <div className="company_logo">
                                    <Image alt = "company logo" loader={this.customImgLoader} src={this.props.data.profile.company_logo} width={150} height={50}/>
                                </div>
                                <div className="ovale fill">Contacter</div>
                            </div>
                        </div>
                        <div className="bottom p2em color-primary">
                            <div className=" company_desc auto border">
                                {this.props.data.profile.company_history}  
                            </div>
                            <div className="overflowH center orientationV">
                                <div className="maps">
                                    <Map
                                        google={this.props.google}
                                        zoom={14}
                                        style={this.state.mapStyles}
                                        initialCenter={this.state.location.pos}
                                    >
                                        <Marker
                                            onClick={this.onMarkerClick}
                                            name={'Kenyatta International Convention Centre'}
                                        />
                                        <InfoWindow
                                            marker={this.state.activeMarker}
                                            visible={this.state.showingInfoWindow}
                                            onClose={this.onClose}
                                        >
                                            <div>
                                                <h4>{this.state.selectedPlace.name}</h4>
                                            </div>
                                        </InfoWindow>
                                    </Map>
                                </div>
                                <br></br>
                                <div className="company_data ">
                                    <div><span> {this.props.data.profile.company_name}</span></div>
                                    <div>&nbsp; {this.props.data.profile.company_rcs}</div>
                                    <div>&nbsp;{this.props.data.profile.company_headquarters}</div>
                                    <div>&nbsp;{this.props.data.profile.company_address}</div>
                                    <div>&nbsp;{this.props.data.profile.company_zip_code}</div>
                                    <div>&nbsp;{this.props.data.profile.company_city}</div>
                                    <div>&nbsp;{this.props.data.profile.company_department}</div>
                                    <div>&nbsp;Tel :{this.props.data.profile.company_phone_number}</div> 
                                    <br></br>
                                </div>
                            </div>
                        </div>
                    </main>


                </div>
                <Footer/>
            </div>
        )
    }
}

export default GoogleApiWrapper({
    apiKey: key
})(index);

export async function getStaticPaths() {
    
    const paths = await getProfilesName()
    //console.log(paths)
    return {
        paths,
        fallback: false
    }
}


export async function getStaticProps({ params }) {

    const data = await getCompanyData(params.id)

    return {
      props: {
        data
      }
    }
}

