import React ,{useState,useEffect,Component}from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Header from '../../components/header/public_header'
import Footer from '../../components/footer/footer'
import Axios from 'axios'
import Image from 'next/image'
import {getProfilesName,getProfileData} from '../../lib/profil'
import { Map, GoogleApiWrapper, InfoWindow, Marker } from 'google-maps-react';

const key = "AIzaSyBeM-wkqt3uIlMXGxnCHAvlsI8EBqXLOQI"



class index extends Component {

    state={

        mapStyles : {
            width: '100%',
            height: '100%',
            overflow: 'hidden',
            position:'relative'
        },
        location : JSON.parse(`${this.props.data.profile.company_location}`),
        
    }


    render() {
        console.log(this.state.location)
        return (
            <div className="recruteur">

                <div className="interface-layout">
                    <Head>
                        <title>A recruit | {this.props.data.profile.company_name}</title>
                        <meta name="description" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    {/*---------------*/}
                    <Header
                        callback = {()=>{setShow_hide3(!show_hide3);}}
                    />
                    {/*---------------*/}
                    
                    <main className="body">

                        <div className="top">
                            <div className="title">
                                <div>
                                    <span>{this.props.data.profile.company_activity}</span>
                                </div>
                                <div>
                                    <br></br>
                                    {this.props.data.profile.company_name}
                                </div>
                            </div>

                            <div className="preview">
                                <div><span>{this.props.data.profile.company_name}</span></div>
                                <br></br>
                                <div className="company_logo">
                                    <Image alt = "company logo" src="/images/partner/partner_audi.svg" width={150} height={50}/>
                                </div>
                                <div className="ovale fill">Contacter</div>
                            </div>
                        </div>
                        <div className="bottom color-primary">
                            <div className=" company_desc auto border">
                                {this.props.data.profile.company_history}  
                            </div>
                            <div className="overflowH center orientationV">
                                <div className="maps">
                                    <Map
                                        style={this.state.mapStyles}
                                        google={google}
                                        zoom={14}
                                        initialCenter={this.state.location.pos}
                                    >
                                        <Marker
                                            position={this.state.location.pos}
                                            name={this.state.location.address}
                                        />
                                    
                                    </Map>
                                </div>
                                <br></br>
                                <div className="company_data ">
                                    <div><span> {this.props.data.profile.company_name}</span></div>
                                    <div>&nbsp; {this.props.data.profile.company_rcs}</div>
                                    <div>&nbsp;{this.props.data.profile.company_headquarters}</div>
                                    <div>&nbsp;{this.props.data.profile.company_address}</div>
                                    <div>&nbsp;{this.props.data.profile.company_zip_code}</div>
                                    <div>&nbsp;{this.props.data.profile.company_city}</div>
                                    <div>&nbsp;{this.props.data.profile.company_department}</div>
                                    <div>&nbsp;Tel :{this.props.data.profile.company_phone_number}</div> 
                                </div>
                            </div>
                        </div>
                    </main>

                    {/*---------------*/}
                    <Footer/>

                </div>
            </div>
        )
    }
}

export default GoogleApiWrapper({
    apiKey: key
})(index);

export async function getStaticPaths() {
    
    const paths = await getProfilesName()
    //console.log(paths)
    return {
        paths,
        fallback: false
    }
}


export async function getStaticProps({ params }) {

    const data = await getProfileData(params.id)

    return {
      props: {
        data
      }
    }
}

